const relatedRecipesObj = {
	data: [
		{
			vegetarian: true,
			vegan: false,
			glutenFree: false,
			dairyFree: false,
			veryHealthy: false,
			cheap: false,
			veryPopular: false,
			sustainable: false,
			weightWatcherSmartPoints: 7,
			gaps: "no",
			lowFodmap: false,
			preparationMinutes: 10,
			cookingMinutes: 30,
			aggregateLikes: 0,
			spoonacularScore: 11,
			healthScore: 1,
			creditsText: "Food.com",
			sourceName: "Food.com",
			pricePerServing: 21.25,
			extendedIngredients: [
				{
					id: 18371,
					aisle: "Baking",
					image: "white-powder.jpg",
					consistency: "solid",
					name: "baking powder",
					original: "1/2 teaspoon baking powder",
					originalString: "1/2 teaspoon baking powder",
					originalName: "baking powder",
					amount: 0.5,
					unit: "teaspoon",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 18372,
					aisle: "Baking",
					image: "white-powder.jpg",
					consistency: "solid",
					name: "baking soda",
					original: "1/2 teaspoon baking soda",
					originalString: "1/2 teaspoon baking soda",
					originalName: "baking soda",
					amount: 0.5,
					unit: "teaspoon",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 1001,
					aisle: "Milk, Eggs, Other Dairy",
					image: "butter-sliced.jpg",
					consistency: "solid",
					name: "butter",
					original: "60 g butter (soft & cut into small cubes)",
					originalString: "60 g butter (soft & cut into small cubes)",
					originalName: "butter (soft & cut into small cubes)",
					amount: 60,
					unit: "g",
					meta: ["soft", "cut into small cubes)"],
					metaInformation: ["soft", "cut into small cubes)"],
					measures: {
						us: {
							amount: 2.116,
							unitShort: "oz",
							unitLong: "ounces",
						},
						metric: {
							amount: 60,
							unitShort: "g",
							unitLong: "grams",
						},
					},
				},
				{
					id: 1230,
					aisle: "Milk, Eggs, Other Dairy",
					image: "buttermilk.jpg",
					consistency: "solid",
					name: "buttermilk",
					original: "1/2 cup buttermilk",
					originalString: "1/2 cup buttermilk",
					originalName: "buttermilk",
					amount: 0.5,
					unit: "cup",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "cups",
							unitLong: "cups",
						},
						metric: {
							amount: 118.294,
							unitShort: "ml",
							unitLong: "milliliters",
						},
					},
				},
				{
					id: 2010,
					aisle: "Spices and Seasonings",
					image: "cinnamon.jpg",
					consistency: "solid",
					name: "cinnamon",
					original: "3/4 teaspoon cinnamon (or more if you like...)",
					originalString: "3/4 teaspoon cinnamon (or more if you like...)",
					originalName: "cinnamon (or more if you like...)",
					amount: 0.75,
					unit: "teaspoon",
					meta: ["( if you like...)"],
					metaInformation: ["( if you like...)"],
					measures: {
						us: {
							amount: 0.75,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.75,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 1123,
					aisle: "Milk, Eggs, Other Dairy",
					image: "egg.png",
					consistency: "solid",
					name: "egg",
					original: "1 large egg",
					originalString: "1 large egg",
					originalName: "egg",
					amount: 1,
					unit: "large",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 1,
							unitShort: "large",
							unitLong: "large",
						},
						metric: {
							amount: 1,
							unitShort: "large",
							unitLong: "large",
						},
					},
				},
				{
					id: 20081,
					aisle: "Baking",
					image: "flour.png",
					consistency: "solid",
					name: "flour",
					original: "1 1/4 cups all-purpose flour (unpacked)",
					originalString: "1 1/4 cups all-purpose flour (unpacked)",
					originalName: "all-purpose flour (unpacked)",
					amount: 1.25,
					unit: "cups",
					meta: ["all-purpose", "(unpacked)"],
					metaInformation: ["all-purpose", "(unpacked)"],
					measures: {
						us: {
							amount: 1.25,
							unitShort: "cups",
							unitLong: "cups",
						},
						metric: {
							amount: 295.735,
							unitShort: "ml",
							unitLong: "milliliters",
						},
					},
				},
				{
					id: 1082047,
					aisle: "Spices and Seasonings",
					image: "salt.jpg",
					consistency: "solid",
					name: "kosher salt",
					original: "1 pinch kosher salt",
					originalString: "1 pinch kosher salt",
					originalName: "kosher salt",
					amount: 1,
					unit: "pinch",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 1,
							unitShort: "pinch",
							unitLong: "pinch",
						},
						metric: {
							amount: 1,
							unitShort: "pinch",
							unitLong: "pinch",
						},
					},
				},
				{
					id: 19334,
					aisle: "Baking",
					image: "light-brown-sugar.jpg",
					consistency: "solid",
					name: "light brown sugar",
					original: "2/3 cup light brown sugar",
					originalString: "2/3 cup light brown sugar",
					originalName: "light brown sugar",
					amount: 0.6666666666666666,
					unit: "cup",
					meta: ["light"],
					metaInformation: ["light"],
					measures: {
						us: {
							amount: 0.667,
							unitShort: "cups",
							unitLong: "cups",
						},
						metric: {
							amount: 157.725,
							unitShort: "ml",
							unitLong: "milliliters",
						},
					},
				},
				{
					id: 2050,
					aisle: "Baking",
					image: "vanilla-extract.jpg",
					consistency: "liquid",
					name: "vanilla extract",
					original: "1 teaspoon vanilla extract",
					originalString: "1 teaspoon vanilla extract",
					originalName: "vanilla extract",
					amount: 1,
					unit: "teaspoon",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 1,
							unitShort: "tsp",
							unitLong: "teaspoon",
						},
						metric: {
							amount: 1,
							unitShort: "tsp",
							unitLong: "teaspoon",
						},
					},
				},
			],
			id: 130933,
			title: "Low Fat Crumbs Cake (Kosher-Dairy)",
			readyInMinutes: 40,
			servings: 10,
			sourceUrl: "http://www.food.com/recipe/low-fat-crumbs-cake-kosher-dairy-150647",
			image: "https://spoonacular.com/recipeImages/130933-556x370.jpg",
			imageType: "jpg",
			summary:
				'Low Fat Crumbs Cake (Kosher-Dairy) might be just the morn meal you are searching for. This recipe makes 10 servings with <b>171 calories</b>, <b>3g of protein</b>, and <b>6g of fat</b> each. For <b>21 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. Head to the store and pick up cinnamon, kosher salt, butter, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>40 minutes</b>. It is a good option if you\'re following a <b>vegetarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 13%</b>. This score is rather bad. Try <a href="https://spoonacular.com/recipes/rich-low-fat-chocolate-cake-kosher-dairy-131757">Rich Low Fat Chocolate Cake (Kosher-Dairy)</a>, <a href="https://spoonacular.com/recipes/low-fat-cinnamon-energy-balls-909039">Low-Fat Cinnamon Energy Balls</a>, and <a href="https://spoonacular.com/recipes/low-carb-bagels-coconut-flour-fat-head-dough-912856">Low Carb Bagels – Coconut Flour Fat Head Dough</a> for similar recipes.',
			cuisines: [],
			dishTypes: ["side dish"],
			diets: ["lacto ovo vegetarian"],
			occasions: [],
			winePairing: {},
			instructions: null,
			analyzedInstructions: [],
			originalId: null,
		},
		{
			vegetarian: false,
			vegan: false,
			glutenFree: false,
			dairyFree: true,
			veryHealthy: true,
			cheap: false,
			veryPopular: false,
			sustainable: false,
			weightWatcherSmartPoints: 7,
			gaps: "no",
			lowFodmap: false,
			aggregateLikes: 187,
			spoonacularScore: 97,
			healthScore: 55,
			creditsText: "Greatist",
			sourceName: "Greatist",
			pricePerServing: 139.54,
			extendedIngredients: [
				{
					id: 9037,
					aisle: "Produce",
					image: "avocado.jpg",
					consistency: "solid",
					name: "avocado",
					original: "1 medium ripe avocado, pitted",
					originalString: "1 medium ripe avocado, pitted",
					originalName: "ripe avocado, pitted",
					amount: 1,
					unit: "medium",
					meta: ["pitted", "ripe"],
					metaInformation: ["pitted", "ripe"],
					measures: {
						us: {
							amount: 1,
							unitShort: "medium",
							unitLong: "medium",
						},
						metric: {
							amount: 1,
							unitShort: "medium",
							unitLong: "medium",
						},
					},
				},
				{
					id: 10211821,
					aisle: "Produce",
					image: "bell-pepper-orange.png",
					consistency: "solid",
					name: "bell pepper",
					original: "Freshly ground black pepper, to taste",
					originalString: "Freshly ground black pepper, to taste",
					originalName: "Freshly ground black pepper, to taste",
					amount: 2,
					unit: "servings",
					meta: ["black", "freshly ground", "to taste"],
					metaInformation: ["black", "freshly ground", "to taste"],
					measures: {
						us: {
							amount: 2,
							unitShort: "servings",
							unitLong: "servings",
						},
						metric: {
							amount: 2,
							unitShort: "servings",
							unitLong: "servings",
						},
					},
				},
				{
					id: 2044,
					aisle: "Produce;Spices and Seasonings",
					image: "basil.jpg",
					consistency: "solid",
					name: "fresh basil",
					original: "1/4 cup Fresh Basil, (optional)",
					originalString: "1/4 cup Fresh Basil, (optional)",
					originalName: "Fresh Basil, (optional)",
					amount: 0.25,
					unit: "cup",
					meta: ["fresh"],
					metaInformation: ["fresh"],
					measures: {
						us: {
							amount: 0.25,
							unitShort: "cups",
							unitLong: "cups",
						},
						metric: {
							amount: 59.147,
							unitShort: "ml",
							unitLong: "milliliters",
						},
					},
				},
				{
					id: 11215,
					aisle: "Produce",
					image: "garlic.png",
					consistency: "solid",
					name: "garlic cloves",
					original: "2-3 garlic cloves, to taste",
					originalString: "2-3 garlic cloves, to taste",
					originalName: "garlic cloves, to taste",
					amount: 2,
					unit: "",
					meta: ["to taste"],
					metaInformation: ["to taste"],
					measures: {
						us: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 9152,
					aisle: "Produce",
					image: "lemon-juice.jpg",
					consistency: "liquid",
					name: "juice of lemon",
					original: "1/2 lemon, juiced + lemon zest to garnish",
					originalString: "1/2 lemon, juiced + lemon zest to garnish",
					originalName: "lemon, juiced + lemon zest to garnish",
					amount: 0.5,
					unit: "",
					meta: ["juiced"],
					metaInformation: ["juiced"],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 0.5,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 1082047,
					aisle: "Spices and Seasonings",
					image: "salt.jpg",
					consistency: "solid",
					name: "kosher salt",
					original: "1/2 tsp kosher salt, or to taste",
					originalString: "1/2 tsp kosher salt, or to taste",
					originalName: "kosher salt, or to taste",
					amount: 0.5,
					unit: "tsp",
					meta: ["to taste"],
					metaInformation: ["to taste"],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 20420,
					aisle: "Pasta and Rice",
					image: "fusilli.jpg",
					consistency: "solid",
					name: "pasta",
					original: "2 servings/6 oz of pasta",
					originalString: "2 servings/6 oz of pasta",
					originalName: "servings/6 oz of pasta",
					amount: 2,
					unit: "",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
					},
				},
			],
			id: 21754,
			title: "My Creamy Avocado Pasta",
			readyInMinutes: 45,
			servings: 2,
			sourceUrl: "http://greatist.com/team/creamy-avocado-pasta/",
			image: "https://spoonacular.com/recipeImages/21754-556x370.jpg",
			imageType: "jpg",
			summary:
				'Need a <b>dairy free side dish</b>? My Creamy Avocado Pasta could be a spectacular recipe to try. This recipe makes 2 servings with <b>227 calories</b>, <b>4g of protein</b>, and <b>15g of fat</b> each. For <b>$1.02 per serving</b>, this recipe <b>covers 11%</b> of your daily requirements of vitamins and minerals. This recipe from Greatist has 187 fans. If you have avocado, garlic cloves, juice of lemon, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 87%</b>. This score is great. Try <a href="https://spoonacular.com/recipes/creamy-avocado-pasta-590599">Creamy Avocado Pasta</a>, <a href="https://spoonacular.com/recipes/creamy-avocado-pasta-547775">Creamy Avocado Pasta</a>, and <a href="https://spoonacular.com/recipes/the-best-creamy-avocado-pasta-ever-553464">The best creamy avocado pastan ever</a> for similar recipes.',
			cuisines: [],
			dishTypes: ["side dish"],
			diets: ["dairy free"],
			occasions: [],
			winePairing: {
				pairedWines: [],
				pairingText:
					"No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
				productMatches: [],
			},
			instructions: null,
			analyzedInstructions: [],
			originalId: null,
		},
		{
			vegetarian: true,
			vegan: false,
			glutenFree: false,
			dairyFree: false,
			veryHealthy: true,
			cheap: false,
			veryPopular: false,
			sustainable: false,
			weightWatcherSmartPoints: 18,
			gaps: "no",
			lowFodmap: false,
			aggregateLikes: 243,
			spoonacularScore: 99,
			healthScore: 98,
			creditsText: "The Healthy Foodie",
			sourceName: "The Healthy Foodie",
			pricePerServing: 483.31,
			extendedIngredients: [
				{
					id: 11011,
					aisle: "Produce",
					image: "asparagus.png",
					consistency: "solid",
					name: "asparagus",
					original: "12 asparagus, cut into 2-3 inch pieces",
					originalString: "12 asparagus, cut into 2-3 inch pieces",
					originalName: "asparagus, cut into 2-3 inch pieces",
					amount: 12,
					unit: "",
					meta: ["cut into 2-3 inch pieces"],
					metaInformation: ["cut into 2-3 inch pieces"],
					measures: {
						us: {
							amount: 12,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 12,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 9037,
					aisle: "Produce",
					image: "avocado.jpg",
					consistency: "solid",
					name: "avocado",
					original: "1 ripe avocado",
					originalString: "1 ripe avocado",
					originalName: "ripe avocado",
					amount: 1,
					unit: "",
					meta: ["ripe"],
					metaInformation: ["ripe"],
					measures: {
						us: {
							amount: 1,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 1,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 11213,
					aisle: "Produce",
					image: "escarole.jpg",
					consistency: "solid",
					name: "endive",
					original: "1 large endive, shredded",
					originalString: "1 large endive, shredded",
					originalName: "endive, shredded",
					amount: 1,
					unit: "large",
					meta: ["shredded"],
					metaInformation: ["shredded"],
					measures: {
						us: {
							amount: 1,
							unitShort: "large",
							unitLong: "large",
						},
						metric: {
							amount: 1,
							unitShort: "large",
							unitLong: "large",
						},
					},
				},
				{
					id: 1011256,
					aisle: "Milk, Eggs, Other Dairy",
					image: "plain-yogurt.jpg",
					consistency: "liquid",
					name: "fat free greek yogurt",
					original: "1 cup fat free plain Greek yogurt",
					originalString: "1 cup fat free plain Greek yogurt",
					originalName: "fat free plain Greek yogurt",
					amount: 1,
					unit: "cup",
					meta: ["plain", "fat free"],
					metaInformation: ["plain", "fat free"],
					measures: {
						us: {
							amount: 1,
							unitShort: "cup",
							unitLong: "cup",
						},
						metric: {
							amount: 236.588,
							unitShort: "ml",
							unitLong: "milliliters",
						},
					},
				},
				{
					id: 9160,
					aisle: "Produce",
					image: "lime-juice.png",
					consistency: "liquid",
					name: "juice of lime",
					original: "The juice of half a lime",
					originalString: "The juice of half a lime",
					originalName: "The juice of half a lime",
					amount: 2,
					unit: "",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 1002030,
					aisle: "Spices and Seasonings",
					image: "pepper.jpg",
					consistency: "solid",
					name: "pepper",
					original: "¼ tsp freshly cracked black pepper",
					originalString: "¼ tsp freshly cracked black pepper",
					originalName: "freshly cracked black pepper",
					amount: 0.25,
					unit: "tsp",
					meta: ["black"],
					metaInformation: ["black"],
					measures: {
						us: {
							amount: 0.25,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.25,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 1032047,
					aisle: "Spices and Seasonings;Gourmet",
					image: "himalayan-pink-salt.jpg",
					consistency: "solid",
					name: "pink himalayan salt",
					original: "½ tsp Himalayan or fine salt",
					originalString: "½ tsp Himalayan or fine salt",
					originalName: "Himalayan or fine salt",
					amount: 0.5,
					unit: "tsp",
					meta: ["fine"],
					metaInformation: ["fine"],
					measures: {
						us: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
						metric: {
							amount: 0.5,
							unitShort: "tsps",
							unitLong: "teaspoons",
						},
					},
				},
				{
					id: 20114,
					aisle: "Pasta and Rice;Ethnic Foods",
					image: "uncooked-soba-noodles.png",
					consistency: "solid",
					name: "soba noodles",
					original: "160g soba noodles",
					originalString: "160g soba noodles",
					originalName: "soba noodles",
					amount: 160,
					unit: "g",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 5.644,
							unitShort: "oz",
							unitLong: "ounces",
						},
						metric: {
							amount: 160,
							unitShort: "g",
							unitLong: "grams",
						},
					},
				},
				{
					id: 12155,
					aisle: "Nuts;Baking",
					image: "walnuts.jpg",
					consistency: "solid",
					name: "walnuts",
					original: "40g walnuts, chopped",
					originalString: "40g walnuts, chopped",
					originalName: "walnuts, chopped",
					amount: 40,
					unit: "g",
					meta: ["chopped"],
					metaInformation: ["chopped"],
					measures: {
						us: {
							amount: 1.411,
							unitShort: "oz",
							unitLong: "ounces",
						},
						metric: {
							amount: 40,
							unitShort: "g",
							unitLong: "grams",
						},
					},
				},
			],
			id: 551035,
			title: "Creamy Avocado Pasta",
			readyInMinutes: 45,
			servings: 2,
			sourceUrl: "http://thehealthyfoodie.com/creamy-avocado-pasta/",
			image: "https://spoonacular.com/recipeImages/551035-556x370.jpg",
			imageType: "jpg",
			summary:
				'Creamy Avocado Pastan is a <b>vegetarian</b> main course. This recipe makes 2 servings with <b>685 calories</b>, <b>32g of protein</b>, and <b>29g of fat</b> each. For <b>$4.7 per serving</b>, this recipe <b>covers 48%</b> of your daily requirements of vitamins and minerals. This recipe from The Healthy Foodie has 243 fans. Head to the store and pick up asparagus, avocado, walnuts, and a few other things to make it today. To use up the avocado you could follow this main course with the <a href="https://spoonacular.com/recipes/chocolate-avocado-mousse-quick-dark-chocolate-avocado-mousse-486646">chocolate avocado mousse | quick dark chocolate avocado mousse</a> as a dessert. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/my-creamy-avocado-pasta-21754">My Creamy Avocado Pasta</a>, <a href="https://spoonacular.com/recipes/creamy-avocado-pasta-512701">Creamy Avocado Pasta</a>, and <a href="https://spoonacular.com/recipes/the-best-creamy-avocado-pasta-ever-553464">The best creamy avocado pastan ever</a> for similar recipes.',
			cuisines: [],
			dishTypes: ["lunch", "main course", "main dish", "dinner"],
			diets: ["lacto ovo vegetarian"],
			occasions: [],
			winePairing: {
				pairedWines: [],
				pairingText:
					"No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
				productMatches: [],
			},
			instructions:
				"Cook pasta according to instructions on package;In the meantime, heat about a teaspoon of olive oil (or use cooking spray) in a medium non stick pan over medium heat and cook the endive and asparagus for 2-3 minutes, until just tender. Remove from heat but leave in pan.Add avocado, yogurt, lemon juice, salt and pepper to the bowl of your food processor and process until smooth.When pasta is cooked, drain it and add it to your reserved vegetables. Add avocado mixture and chopped walnuts and toss delicately to combine.Serve immediately.",
			analyzedInstructions: [
				{
					name: "",
					steps: [
						{
							number: 1,
							step:
								"Cook pasta according to instructions on package;In the meantime, heat about a teaspoon of olive oil (or use cooking spray) in a medium non stick pan over medium heat and cook the endive and asparagus for 2-3 minutes, until just tender.",
							ingredients: [
								{
									id: 4679,
									name: "cooking spray",
									localizedName: "cooking spray",
									image: "cooking-spray.png",
								},
								{
									id: 11011,
									name: "asparagus",
									localizedName: "asparagus",
									image: "asparagus.png",
								},
								{
									id: 4053,
									name: "olive oil",
									localizedName: "olive oil",
									image: "olive-oil.jpg",
								},
								{
									id: 11213,
									name: "endive",
									localizedName: "endive",
									image: "escarole.jpg",
								},
								{
									id: 20420,
									name: "pasta",
									localizedName: "pasta",
									image: "fusilli.jpg",
								},
							],
							equipment: [
								{
									id: 404645,
									name: "frying pan",
									localizedName: "frying pan",
									image: "pan.png",
								},
							],
							length: {
								number: 3,
								unit: "minutes",
							},
						},
						{
							number: 2,
							step: "Remove from heat but leave in pan.",
							ingredients: [],
							equipment: [
								{
									id: 404645,
									name: "frying pan",
									localizedName: "frying pan",
									image: "pan.png",
								},
							],
						},
						{
							number: 3,
							step:
								"Add avocado, yogurt, lemon juice, salt and pepper to the bowl of your food processor and process until smooth.When pasta is cooked, drain it and add it to your reserved vegetables.",
							ingredients: [
								{
									id: 1102047,
									name: "salt and pepper",
									localizedName: "salt and pepper",
									image: "salt-and-pepper.jpg",
								},
								{
									id: 9152,
									name: "lemon juice",
									localizedName: "lemon juice",
									image: "lemon-juice.jpg",
								},
								{
									id: 11583,
									name: "vegetable",
									localizedName: "vegetable",
									image: "mixed-vegetables.png",
								},
								{
									id: 9037,
									name: "avocado",
									localizedName: "avocado",
									image: "avocado.jpg",
								},
								{
									id: 1116,
									name: "yogurt",
									localizedName: "yogurt",
									image: "plain-yogurt.jpg",
								},
								{
									id: 20420,
									name: "pasta",
									localizedName: "pasta",
									image: "fusilli.jpg",
								},
							],
							equipment: [
								{
									id: 404771,
									name: "food processor",
									localizedName: "food processor",
									image: "food-processor.png",
								},
								{
									id: 404783,
									name: "bowl",
									localizedName: "bowl",
									image: "bowl.jpg",
								},
							],
						},
						{
							number: 4,
							step: "Add avocado mixture and chopped walnuts and toss delicately to combine.",
							ingredients: [
								{
									id: 12155,
									name: "walnut pieces",
									localizedName: "walnut pieces",
									image: "walnuts.jpg",
								},
								{
									id: 9037,
									name: "avocado",
									localizedName: "avocado",
									image: "avocado.jpg",
								},
							],
							equipment: [],
						},
						{
							number: 5,
							step: "Serve immediately.",
							ingredients: [],
							equipment: [],
						},
					],
				},
			],
			originalId: null,
		},
		{
			vegetarian: true,
			vegan: true,
			glutenFree: false,
			dairyFree: true,
			veryHealthy: true,
			cheap: false,
			veryPopular: false,
			sustainable: false,
			weightWatcherSmartPoints: 10,
			gaps: "no",
			lowFodmap: false,
			preparationMinutes: 15,
			cookingMinutes: 0,
			aggregateLikes: 46,
			spoonacularScore: 99,
			healthScore: 100,
			creditsText: "Simply Being Mommy",
			sourceName: "Simply Being Mommy",
			pricePerServing: 121.39,
			extendedIngredients: [
				{
					id: 9037,
					aisle: "Produce",
					image: "avocado.jpg",
					consistency: "solid",
					name: "avocado",
					original: "1 medium ripe Avocado, pitted",
					originalString: "1 medium ripe Avocado, pitted",
					originalName: "ripe Avocado, pitted",
					amount: 1,
					unit: "medium",
					meta: ["pitted", "ripe"],
					metaInformation: ["pitted", "ripe"],
					measures: {
						us: {
							amount: 1,
							unitShort: "medium",
							unitLong: "medium",
						},
						metric: {
							amount: 1,
							unitShort: "medium",
							unitLong: "medium",
						},
					},
				},
				{
					id: 10211821,
					aisle: "Produce",
					image: "bell-pepper-orange.png",
					consistency: "solid",
					name: "bell pepper",
					original: "Freshly ground black pepper, to taste",
					originalString: "Freshly ground black pepper, to taste",
					originalName: "Freshly ground black pepper, to taste",
					amount: 4,
					unit: "servings",
					meta: ["black", "freshly ground", "to taste"],
					metaInformation: ["black", "freshly ground", "to taste"],
					measures: {
						us: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
						metric: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
					},
				},
				{
					id: 1034053,
					aisle: "Oil, Vinegar, Salad Dressing",
					image: "olive-oil.jpg",
					consistency: "liquid",
					name: "extra virgin olive oil",
					original: "2 tbsp extra virgin olive oil",
					originalString: "2 tbsp extra virgin olive oil",
					originalName: "extra virgin olive oil",
					amount: 2,
					unit: "tbsp",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 2,
							unitShort: "Tbsps",
							unitLong: "Tbsps",
						},
						metric: {
							amount: 2,
							unitShort: "Tbsps",
							unitLong: "Tbsps",
						},
					},
				},
				{
					id: 11215,
					aisle: "Produce",
					image: "garlic.png",
					consistency: "solid",
					name: "garlic cloves",
					original: "2-3 garlic cloves, to taste",
					originalString: "2-3 garlic cloves, to taste",
					originalName: "garlic cloves, to taste",
					amount: 2,
					unit: "",
					meta: ["to taste"],
					metaInformation: ["to taste"],
					measures: {
						us: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 2,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 9152,
					aisle: "Produce",
					image: "lemon-juice.jpg",
					consistency: "liquid",
					name: "juice of lemon",
					original: "1 lemon, juiced",
					originalString: "1 lemon, juiced",
					originalName: "lemon, juiced",
					amount: 1,
					unit: "",
					meta: ["juiced"],
					metaInformation: ["juiced"],
					measures: {
						us: {
							amount: 1,
							unitShort: "",
							unitLong: "",
						},
						metric: {
							amount: 1,
							unitShort: "",
							unitLong: "",
						},
					},
				},
				{
					id: 1082047,
					aisle: "Spices and Seasonings",
					image: "salt.jpg",
					consistency: "solid",
					name: "kosher salt",
					original: "kosher salt, or to taste",
					originalString: "kosher salt, or to taste",
					originalName: "kosher salt, or to taste",
					amount: 4,
					unit: "servings",
					meta: ["to taste"],
					metaInformation: ["to taste"],
					measures: {
						us: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
						metric: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
					},
				},
				{
					id: 9156,
					aisle: "Produce",
					image: "zest-lemon.jpg",
					consistency: "solid",
					name: "lemon zest",
					original: "lemon zest to garnish",
					originalString: "lemon zest to garnish",
					originalName: "lemon zest to garnish",
					amount: 4,
					unit: "servings",
					meta: [],
					metaInformation: [],
					measures: {
						us: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
						metric: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
					},
				},
				{
					id: 10020124,
					aisle: "Pasta and Rice",
					image: "whole-wheat-spaghetti.jpg",
					consistency: "solid",
					name: "whole wheat spaghetti noodles",
					original: "4 servings of whole wheat spaghetti noodles",
					originalString: "4 servings of whole wheat spaghetti noodles",
					originalName: "whole wheat spaghetti noodles",
					amount: 4,
					unit: "servings",
					meta: ["whole wheat"],
					metaInformation: ["whole wheat"],
					measures: {
						us: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
						metric: {
							amount: 4,
							unitShort: "servings",
							unitLong: "servings",
						},
					},
				},
			],
			id: 512701,
			title: "Creamy Avocado Pasta",
			readyInMinutes: 15,
			servings: 4,
			sourceUrl: "http://simplybeingmommy.com/2011/06/19/creamy-avocado-pasta/",
			image: "https://spoonacular.com/recipeImages/512701-556x370.jpg",
			imageType: "jpg",
			summary:
				'Creamy Avocado Pasta might be just the side dish you are searching for. This recipe makes 4 servings with <b>341 calories</b>, <b>9g of protein</b>, and <b>15g of fat</b> each. For <b>84 cents per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. 46 people were impressed by this recipe. From preparation to the plate, this recipe takes roughly <b>15 minutes</b>. It is a good option if you\'re following a <b>vegan</b> diet. A mixture of avocado, pepper, kosher salt, and a handful of other ingredients are all it takes to make this recipe so scrumptious. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is excellent. Try <a href="https://spoonacular.com/recipes/creamy-avocado-pasta-590599">Creamy Avocado Pasta</a>, <a href="https://spoonacular.com/recipes/my-creamy-avocado-pasta-21754">My Creamy Avocado Pasta</a>, and <a href="https://spoonacular.com/recipes/creamy-avocado-pasta-551035">Creamy Avocado Pasta</a> for similar recipes.',
			cuisines: [],
			dishTypes: ["side dish"],
			diets: ["dairy free", "lacto ovo vegetarian", "vegan"],
			occasions: [],
			winePairing: {
				pairedWines: [],
				pairingText:
					"No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
				productMatches: [],
			},
			instructions:
				"Bring salted water to a boil in a medium sized pot. Add in pasta and reduce heat to medium and cook until Al Dente.In a food processor, make the sauce by placing the garlic cloves, lemon juice, and olive oil blending until smooth. Add in the pitted avocado and salt. Continue to process until smooth and creamy.When pasta is done cooking, drain and place pasta into a large bowl. Pour sauce over noodles and toss until fully combined. Garnish with lemon zest and black pepper. Serve immediately.",
			analyzedInstructions: [
				{
					name: "",
					steps: [
						{
							number: 1,
							step: "Bring salted water to a boil in a medium sized pot.",
							ingredients: [
								{
									id: 14412,
									name: "water",
									localizedName: "water",
									image: "water.png",
								},
							],
							equipment: [
								{
									id: 404752,
									name: "pot",
									localizedName: "pot",
									image: "stock-pot.jpg",
								},
							],
						},
						{
							number: 2,
							step:
								"Add in pasta and reduce heat to medium and cook until Al Dente.In a food processor, make the sauce by placing the garlic cloves, lemon juice, and olive oil blending until smooth.",
							ingredients: [
								{
									id: 10211215,
									name: "whole garlic cloves",
									localizedName: "whole garlic cloves",
									image: "garlic.jpg",
								},
								{
									id: 9152,
									name: "lemon juice",
									localizedName: "lemon juice",
									image: "lemon-juice.jpg",
								},
								{
									id: 4053,
									name: "olive oil",
									localizedName: "olive oil",
									image: "olive-oil.jpg",
								},
								{
									id: 20420,
									name: "pasta",
									localizedName: "pasta",
									image: "fusilli.jpg",
								},
								{
									id: 0,
									name: "sauce",
									localizedName: "sauce",
									image: "",
								},
							],
							equipment: [
								{
									id: 404771,
									name: "food processor",
									localizedName: "food processor",
									image: "food-processor.png",
								},
							],
						},
						{
							number: 3,
							step:
								"Add in the pitted avocado and salt. Continue to process until smooth and creamy.When pasta is done cooking, drain and place pasta into a large bowl.",
							ingredients: [
								{
									id: 9037,
									name: "avocado",
									localizedName: "avocado",
									image: "avocado.jpg",
								},
								{
									id: 20420,
									name: "pasta",
									localizedName: "pasta",
									image: "fusilli.jpg",
								},
								{
									id: 2047,
									name: "salt",
									localizedName: "salt",
									image: "salt.jpg",
								},
							],
							equipment: [
								{
									id: 404783,
									name: "bowl",
									localizedName: "bowl",
									image: "bowl.jpg",
								},
							],
						},
						{
							number: 4,
							step: "Pour sauce over noodles and toss until fully combined.",
							ingredients: [
								{
									id: 20420,
									name: "pasta",
									localizedName: "pasta",
									image: "fusilli.jpg",
								},
								{
									id: 0,
									name: "sauce",
									localizedName: "sauce",
									image: "",
								},
							],
							equipment: [],
						},
						{
							number: 5,
							step: "Garnish with lemon zest and black pepper.",
							ingredients: [
								{
									id: 1002030,
									name: "black pepper",
									localizedName: "black pepper",
									image: "pepper.jpg",
								},
								{
									id: 9156,
									name: "lemon zest",
									localizedName: "lemon zest",
									image: "zest-lemon.jpg",
								},
							],
							equipment: [],
						},
						{
							number: 6,
							step: "Serve immediately.",
							ingredients: [],
							equipment: [],
						},
					],
				},
			],
			originalId: null,
		},
	],
	status: 200,
	statusText: "OK",
	headers: {
		"content-type": "application/json",
	},
	config: {
		url: "https://api.spoonacular.com/recipes/informationBulk",
		method: "get",
		params: {
			apiKey: "cd74bd0589054098a2161681f58192c0",
			ids: "130933,21754,551035,512701",
			includeNutrition: false,
			addRecipeInformation: true,
			fillIngredients: true,
		},
		headers: {
			Accept: "application/json, text/plain, */*",
		},
		transformRequest: [null],
		transformResponse: [null],
		timeout: 0,
		xsrfCookieName: "XSRF-TOKEN",
		xsrfHeaderName: "X-XSRF-TOKEN",
		maxContentLength: -1,
	},
	request: {},
};

export default relatedRecipesObj;
